name: Rust

on:
  push:
    branches:
      - main
      - ci
      - 3.0
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: zitsen/mdbook
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: mdbook build && cp ci/index.html book/ && touch book/.nojekyll && sed -i 's#\.\./\.\./en#../en#' book/zh/*.html && mkdir book/v3 && mv book/en book/zh book/v3/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
